### ISSUE TITLE
Problema de importar los datasets

### ISSUE THREAD

**Issue by Cami1992** [pachamaltese/casen#12]
Seguí las intrucciones del documento Readme pero no he tenido éxito, cómo lo puedo resolver?
> descargar_casen_github(1990, tempdir())
Intentando descargar CASEN 1990...
versuche URL 'https://pachamaltese.github.io/casen/data-rds/1990.rds'
Kann URL 'https://pachamaltese.github.io/casen/data-rds/1990.rds' nicht �ffnen: HTTP Status war '404 Not Found'Error in utils::download.file(u, f, mode = "wb") : 
  kann URL 'https://pachamaltese.github.io/casen/data-rds/1990.rds' nicht öffnen
> descargar_casen_mds(anios = 2017, carpeta = NULL)
Fehler in descargar_casen_mds(anios = 2017, carpeta = NULL) : 
  is.character(carpeta) ist nicht TRUE
> descargar_casen_mds(anios = 2017, carpeta = NULL)
Fehler in descargar_casen_mds(anios = 2017, carpeta = NULL) : 
  is.character(carpeta) ist nicht TRUE

**Comment by pachadotdev** [comment]
@Cami1992 gracias por avisar y disculpa por la demora en ver esto
acabo de corregir la URL, ahora intente con `descargar_casen_github(carpeta = "prueba")` y funciona
subo cambios ahora y envio a CRAN
