### ISSUE TITLE
nombre variable estrato en descripción parámetros

### ISSUE THREAD

**Issue by vcanalesg** [pachamaltese/casen#8]
Hola!
Hay un pequeño error en la descripción de los parámetros de las funciones que aparecen en internals.R. Cuando se describe la variable correspondiente a los estratos de varianza, dice que el nombre es varunit, cuando lo correcto es que el nombre sea varstrat.

Muchas gracias!

<img width="1018" alt="varunit-varstrat" src="https://user-images.githubusercontent.com/42503780/77259208-b8b7cb80-6c5e-11ea-8b91-aed2a1f11624.png">

**Comment by pachadotdev** [comment]
toda la razón, me pasó por hacer copy paste de la línea 6

**Comment by pachadotdev** [comment]
@vcanalesg gracias! lo he solucionado en 467e834be4ef1ccd8f02f8b7fa4d0b7faff34a7a
no lo noté en las viñetas pues era parte de la documentación interna, o sea que el usuario nunca ve eso a manos que haga `casen:::check_input()` (con triple dos puntos)
